add xygeni scanner path

diff --git a/.github/workflows/build_w_safe_dep.yml b/.github/workflows/build_w_safe_dep.yml
--- a/.github/workflows/build_w_safe_dep.yml
+++ b/.github/workflows/build_w_safe_dep.yml
@@ -85,6 +85,9 @@ jobs:
                   # Default: 1
                   fetch-depth: "0"
 
+            - name: Add Xygeni to PATH
+              run: echo "${HOME}/.xygeni" >> $GITHUB_PATH
+
             # Runs a set of commands using the runners shell
             - name:
                   Download Xygeni Scanner
@@ -101,12 +104,10 @@ jobs:
                   cat ${GITHUB_WORKSPACE}/package.json 
                   npm -v
                   echo Executing Xygeni scan ....    
-                  #${GITHUB_WORKSPACE}/scanner/xygeni scan --fail-on=critical --run="inventory,misconf,deps,suspectdeps" --no-conf-download -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/** --skip-detectors=any=low
-                  ${GITHUB_WORKSPACE}/scanner/xygeni scan  -f none \
+                  ${HOME}/.xygeni/xygeni scan  -f none \
                           --fail-on="file:${GITHUB_WORKSPACE}/GuardRails/deps-critical.xyflow" \
                           --run="inventory,misconf,deps,suspectdeps" --no-conf-download \
                           -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/** --skip-detectors=any=low
-                  #${GITHUB_WORKSPACE}/scanner/xygeni scan --fail-on=file:${GITHUB_WORKSPACE}/lgv.xyflow --include-collaborators -f none --run="inventory,misconf,codetamper" --no-conf-download -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/**
                   retVal=$?
                   if [ $retVal -ne 0 ]; then
                     echo "======================================="
@@ -126,5 +127,37 @@ jobs:
                   echo "::notice $mw::$text"
 
                   exit $retVal
+              # - name: Execution Xygeni Scanner (vuln)
+              #   run: |
+              #       set +e
+              #       rm ./package-lock.json
+              #       cat ${GITHUB_WORKSPACE}/package.json
+              #       npm -v
+              #       echo Executing Xygeni scan ....
+              #       #${GITHUB_WORKSPACE}/scanner/xygeni scan --fail-on=critical --run="inventory,misconf,deps,suspectdeps" --no-conf-download -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/** --skip-detectors=any=low
+              #       ${GITHUB_WORKSPACE}/scanner/xygeni scan  -f none \
+              #               --fail-on="file:${GITHUB_WORKSPACE}/GuardRails/deps-critical.xyflow" \
+              #               --run="inventory,misconf,deps,suspectdeps" --no-conf-download \
+              #               -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/** --skip-detectors=any=low
+              #       #${GITHUB_WORKSPACE}/scanner/xygeni scan --fail-on=file:${GITHUB_WORKSPACE}/lgv.xyflow --include-collaborators -f none --run="inventory,misconf,codetamper" --no-conf-download -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/**
+              #       retVal=$?
+              #       if [ $retVal -ne 0 ]; then
+              #         echo "======================================="
+              #         echo "Detected usage of Dep with Malware !!!! "
+              #         echo " => Dep. Name:    $PKG_NAME"
+              #         echo " => Dep. Version: $PKG_VERSION"
+              #         echo "Breaking the build to avoid malware !!!! "
+              #         echo "======================================="
+              #         text="Detected usage of Dependency ($mw) with Malware !!!! "
+              #         #echo "::error file=app.js,line=10,col=15::$text"
+              #         echo "::error $mw::$text"
+              #         text="Breaking the build to avoid malware infection !!!! "
+              #         #echo "::error file=app.js,line=10,col=15::$text"
+              #         echo "::error $mw::$text"
+              #       fi
+              #       text="No dependencies with malware detected!!!! "
+              #       echo "::notice $mw::$text"
+
+              #       exit $retVal
               env:
                   GITHUB_PAT: ${{ secrets.GH_PAT }}
